export const ErrorCodes = {
  // Auth errors
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_PERMISSION_DENIED: 'AUTH_PERMISSION_DENIED',

  // User errors
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_BLOCKED: 'USER_BLOCKED',

  // Order errors
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_STATUS_ERROR: 'ORDER_STATUS_ERROR',
  ORDER_TIME_CONFLICT: 'ORDER_TIME_CONFLICT',

  // Payment errors
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_REFUND_FAILED: 'PAYMENT_REFUND_FAILED',

  // Demand errors
  DEMAND_NOT_FOUND: 'DEMAND_NOT_FOUND',
  DEMAND_STATUS_ERROR: 'DEMAND_STATUS_ERROR',

  // Consultant errors
  CONSULTANT_NOT_FOUND: 'CONSULTANT_NOT_FOUND',
  CONSULTANT_NOT_APPROVED: 'CONSULTANT_NOT_APPROVED',
  CONSULTANT_CREDIT_LOW: 'CONSULTANT_CREDIT_LOW',

  // Common errors
  INVALID_PARAM: 'INVALID_PARAM',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
} as const;

export type ErrorCode = keyof typeof ErrorCodes;
